//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCafeteria.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoCafeteria.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar_boton {
            get {
                return ResourceManager.GetString("Aceptar_boton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancerlar_boton {
            get {
                return ResourceManager.GetString("Cancerlar_boton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo es inexistente.
        /// </summary>
        public static string CodigoEstadoHTTP_NO_REGISTRADO {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP_NO_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La primer parte de la peticion se recibio correctamente.
        /// </summary>
        public static string CodigoEstadoHTTP100 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor acepto el cambio propuesto por el navegador.
        /// </summary>
        public static string CodigoEstadoHTTP101 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor está procesando la petición del navegador pero todavía no ha terminado.
        /// </summary>
        public static string CodigoEstadoHTTP102 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a reanudar una petición POST o PUT que fue abortada previamente..
        /// </summary>
        public static string CodigoEstadoHTTP103 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operacion se realizo correctamente.
        /// </summary>
        public static string CodigoEstadoHTTP200 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición ha sido completada y ha resultado en la creación de un nuevo recurso..
        /// </summary>
        public static string CodigoEstadoHTTP201 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición ha sido aceptada para procesamiento, pero este no ha sido completado..
        /// </summary>
        public static string CodigoEstadoHTTP202 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición se ha completado con éxito, pero su contenido no se ha obtenido de la fuente originalmente solicitada sino de otro servidor..
        /// </summary>
        public static string CodigoEstadoHTTP203 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición se ha completado con éxito pero su respuesta no tiene ningún contenido.
        /// </summary>
        public static string CodigoEstadoHTTP204 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición se ha completado con éxito, pero su respuesta no tiene contenidos y además, el navegador tiene que inicializar la página desde la que se realizó la petición..
        /// </summary>
        public static string CodigoEstadoHTTP205 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición servirá parcialmente el contenido solicitado..
        /// </summary>
        public static string CodigoEstadoHTTP206 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cuerpo del mensaje que sigue es un mensaje XML y puede contener algún número de códigos de respuesta separados, dependiendo de cuántas sub-peticiones sean hechas..
        /// </summary>
        public static string CodigoEstadoHTTP207 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El listado de elementos DAV ya se notificó previamente, por lo que no se van a volver a listar..
        /// </summary>
        public static string CodigoEstadoHTTP208 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor ha cumplido una petición GET para el recurso y la respuesta es una representación del resultado de una o más manipulaciones de instancia aplicadas a la instancia actual..
        /// </summary>
        public static string CodigoEstadoHTTP226 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ndica opciones múltiples para el URI que el cliente podría seguir..
        /// </summary>
        public static string CodigoEstadoHTTP300 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta y todas las peticiones futuras deberían ser dirigidas a la URL dada..
        /// </summary>
        public static string CodigoEstadoHTTP301 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a el recurso de la URI solicitada ha sido cambiado temporalmente. Nuevos cambios en la URI serán agregados en el futuro..
        /// </summary>
        public static string CodigoEstadoHTTP302 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La respuesta a la petición puede ser encontrada bajo otra URI utilizando el método GET..
        /// </summary>
        public static string CodigoEstadoHTTP303 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la respuesta no ha sido modificada se puede continuar usando la misma versión almacenada en caché..
        /// </summary>
        public static string CodigoEstadoHTTP304 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La respuesta solicitada debe ser accedida desde un proxy..
        /// </summary>
        public static string CodigoEstadoHTTP305 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este codigo esta reservado..
        /// </summary>
        public static string CodigoEstadoHTTP306 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La redirección que debería haber sido hecha con otra URI, sin embargo aún puede ser procesada con la URI proporcionada..
        /// </summary>
        public static string CodigoEstadoHTTP307 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso solicitado por el navegador se encuentra en otro lugar y este cambio es permanente..
        /// </summary>
        public static string CodigoEstadoHTTP308 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no pudo interpretar la solicitud dada una sintaxis inválida..
        /// </summary>
        public static string CodigoEstadoHTTP400 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario autenticar para obtener la respuesta solicitada..
        /// </summary>
        public static string CodigoEstadoHTTP401 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este código de respuesta está reservado para futuros usos..
        /// </summary>
        public static string CodigoEstadoHTTP402 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente no posee los permisos necesarios para cierto contenido, por lo que el servidor está rechazando otorgar una respuesta apropiada..
        /// </summary>
        public static string CodigoEstadoHTTP403 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no pudo encontrar el contenido solicitado..
        /// </summary>
        public static string CodigoEstadoHTTP404 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método solicitado es conocido por el servidor pero ha sido deshabilitado y no puede ser utilizado..
        /// </summary>
        public static string CodigoEstadoHTTP405 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no es capaz de devolver los datos en ninguno de los formatos aceptados por el cliente..
        /// </summary>
        public static string CodigoEstadoHTTP406 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor acepta la solicitud pero se requiere la autenticación del Proxy para que el servidor pueda procesarla..
        /// </summary>
        public static string CodigoEstadoHTTP407 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor quiere desconectar esta conexión sin usar..
        /// </summary>
        public static string CodigoEstadoHTTP408 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no pudo ser procesada debido a un conflicto con el estado actual del recurso que esta identifica..
        /// </summary>
        public static string CodigoEstadoHTTP409 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso solicitado ya no está disponible y no lo estará de nuevo..
        /// </summary>
        public static string CodigoEstadoHTTP410 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor rechazo la petición del navegador porque no incluye la cabecera Content-Length adecuada..
        /// </summary>
        public static string CodigoEstadoHTTP411 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no es capaz de cumplir con algunas de las condiciones impuestas por el navegador en su petición..
        /// </summary>
        public static string CodigoEstadoHTTP412 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición del navegador es demasiado grande y por ese motivo el servidor no la procesa..
        /// </summary>
        public static string CodigoEstadoHTTP413 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La URI de la petición del navegador es demasiado grande y por ese motivo el servidor no la procesa..
        /// </summary>
        public static string CodigoEstadoHTTP414 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición del navegador tiene un formato que no entiende el servidor y por eso no se procesa..
        /// </summary>
        public static string CodigoEstadoHTTP415 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente ha preguntado por una parte de un archivo, pero el servidor no puede proporcionar esa parte..
        /// </summary>
        public static string CodigoEstadoHTTP416 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición del navegador no se procesa porque el servidor no es capaz de cumplir con los requerimientos de la cabecera Expect de la petición..
        /// </summary>
        public static string CodigoEstadoHTTP417 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor se rehúsa a intentar hacer café con una tetera..
        /// </summary>
        public static string CodigoEstadoHTTP418 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición fue dirigida a un servidor que no es capaz de producir una respuesta..
        /// </summary>
        public static string CodigoEstadoHTTP421 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud está bien formada pero fue imposible seguirla debido a errores semánticos..
        /// </summary>
        public static string CodigoEstadoHTTP422 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso al que se está teniendo acceso está bloqueado..
        /// </summary>
        public static string CodigoEstadoHTTP423 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud falló debido a una falla en la solicitud previa..
        /// </summary>
        public static string CodigoEstadoHTTP424 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este codigo esta reservado..
        /// </summary>
        public static string CodigoEstadoHTTP425 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente debería cambiarse a TLS/1.0..
        /// </summary>
        public static string CodigoEstadoHTTP426 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor requiere que la petición del navegador sea condicional..
        /// </summary>
        public static string CodigoEstadoHTTP428 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay muchas conexiones desde esta dirección de internet..
        /// </summary>
        public static string CodigoEstadoHTTP429 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no puede procesar la petición porque una de las cabeceras de la petición es demasiado grande..
        /// </summary>
        public static string CodigoEstadoHTTP431 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una extensión de Microsoft: La petición debería ser reintentada después de hacer la acción apropiada..
        /// </summary>
        public static string CodigoEstadoHTTP449 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contenido ha sido eliminado como consecuencia de una orden judicial o sentencia emitida por un tribunal..
        /// </summary>
        public static string CodigoEstadoHTTP451 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor ha encontrado una situación que no sabe cómo manejarla..
        /// </summary>
        public static string CodigoEstadoHTTP500 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método solicitado no está soportado por el servidor y no puede ser manejado..
        /// </summary>
        public static string CodigoEstadoHTTP501 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor está actuando de proxy o gateway y ha recibido una respuesta inválida del otro servidor, por lo que no puede responder adecuadamente a la petición del navegador..
        /// </summary>
        public static string CodigoEstadoHTTP502 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no puede responder a la petición del navegador porque está congestionado o está realizando tareas de mantenimiento..
        /// </summary>
        public static string CodigoEstadoHTTP503 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor está actuando de proxy o gateway y no ha recibido a tiempo una respuesta del otro servidor, por lo que no puede responder adecuadamente a la petición del navegador..
        /// </summary>
        public static string CodigoEstadoHTTP504 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no soporta o no quiere soportar la versión del protocolo HTTP utilizada en la petición del navegador..
        /// </summary>
        public static string CodigoEstadoHTTP505 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor ha detectado una referencia circular al procesar la parte de la negociación del contenido de la petición..
        /// </summary>
        public static string CodigoEstadoHTTP506 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no puede crear o modificar el recurso solicitado porque no hay suficiente espacio de almacenamiento libre..
        /// </summary>
        public static string CodigoEstadoHTTP507 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición no se puede procesar porque el servidor ha encontrado un bucle infinito al intentar procesarla..
        /// </summary>
        public static string CodigoEstadoHTTP508 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite de ancho de banda excedido..
        /// </summary>
        public static string CodigoEstadoHTTP509 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La petición del navegador debe añadir más extensiones para que el servidor pueda procesarla..
        /// </summary>
        public static string CodigoEstadoHTTP510 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El navegador debe autenticarse para poder realizar peticiones.
        /// </summary>
        public static string CodigoEstadoHTTP511 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor está en una operación de actualizado y no puede tener conexión..
        /// </summary>
        public static string CodigoEstadoHTTP512 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La versión no es compatible con el hardware..
        /// </summary>
        public static string CodigoEstadoHTTP521 {
            get {
                return ResourceManager.GetString("CodigoEstadoHTTP521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme la contraseña.
        /// </summary>
        public static string ConfirmarContrasena_etiqueta {
            get {
                return ResourceManager.GetString("ConfirmarContrasena_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el apellido materno.
        /// </summary>
        public static string IngreseApellidoMaterno_etiqueta {
            get {
                return ResourceManager.GetString("IngreseApellidoMaterno_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su apellido materno.
        /// </summary>
        public static string IngreseApellidoMaternoCliente_etiqueta {
            get {
                return ResourceManager.GetString("IngreseApellidoMaternoCliente_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el apellido paterno.
        /// </summary>
        public static string IngreseApellidoPaterno_etiqueta {
            get {
                return ResourceManager.GetString("IngreseApellidoPaterno_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su apellido paterno.
        /// </summary>
        public static string IngreseApellidoPaternoCliente_etiqueta {
            get {
                return ResourceManager.GetString("IngreseApellidoPaternoCliente_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la cantidad en existencia.
        /// </summary>
        public static string IngreseCantidadExistencia_etiqueta {
            get {
                return ResourceManager.GetString("IngreseCantidadExistencia_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la cantidad de producto.
        /// </summary>
        public static string IngreseCantidadProducto_etiqueta {
            get {
                return ResourceManager.GetString("IngreseCantidadProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese matricula o clave de trabajador.
        /// </summary>
        public static string IngreseClave_etiqueta {
            get {
                return ResourceManager.GetString("IngreseClave_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la clave de trabajador.
        /// </summary>
        public static string IngreseClaveTrabajador_etiqueta {
            get {
                return ResourceManager.GetString("IngreseClaveTrabajador_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su contraseña.
        /// </summary>
        public static string IngreseConfirmacionContrasena {
            get {
                return ResourceManager.GetString("IngreseConfirmacionContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su contraseña.
        /// </summary>
        public static string IngreseContrasena_etiqueta {
            get {
                return ResourceManager.GetString("IngreseContrasena_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la contraseña.
        /// </summary>
        public static string IngreseContrasena_etiquetav {
            get {
                return ResourceManager.GetString("IngreseContrasena_etiquetav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la contraseña.
        /// </summary>
        public static string IngreseContraseñaLogin_etiqueta {
            get {
                return ResourceManager.GetString("IngreseContraseñaLogin_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la descripcion del producto.
        /// </summary>
        public static string IngreseDescripcionProducto_etiqueta {
            get {
                return ResourceManager.GetString("IngreseDescripcionProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la marca del producto.
        /// </summary>
        public static string IngreseMarcaProducto_etiqueta {
            get {
                return ResourceManager.GetString("IngreseMarcaProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su matricula.
        /// </summary>
        public static string IngreseMatricula_etiqueta {
            get {
                return ResourceManager.GetString("IngreseMatricula_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre.
        /// </summary>
        public static string IngreseNombre_etiqueta {
            get {
                return ResourceManager.GetString("IngreseNombre_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su(s) nombre(s).
        /// </summary>
        public static string IngreseNombreCliente_etiqueta {
            get {
                return ResourceManager.GetString("IngreseNombreCliente_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese nombre del producto.
        /// </summary>
        public static string IngreseNombreProducto_etiqueta {
            get {
                return ResourceManager.GetString("IngreseNombreProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el precio del producto.
        /// </summary>
        public static string IngresePrecioProducto_etiqueta {
            get {
                return ResourceManager.GetString("IngresePrecioProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese numero de telefono.
        /// </summary>
        public static string IngreseTelefono_etiqueta {
            get {
                return ResourceManager.GetString("IngreseTelefono_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su numero de telefono.
        /// </summary>
        public static string IngreseTelefonoCliente_etiqueta {
            get {
                return ResourceManager.GetString("IngreseTelefonoCliente_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Aun no tiene cuenta de usuario?.
        /// </summary>
        public static string NoTieneCuenta_etiqueta {
            get {
                return ResourceManager.GetString("NoTieneCuenta_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Registrarse_etiqueta {
            get {
                return ResourceManager.GetString("Registrarse_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de la imagen.
        /// </summary>
        public static string RutaImagen_etiqueta {
            get {
                return ResourceManager.GetString("RutaImagen_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione cantidad de producto.
        /// </summary>
        public static string SeleccioneCantidadProducto_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneCantidadProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la categoria del producto.
        /// </summary>
        public static string SeleccioneCategoriaProducto_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneCategoriaProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el estado del producto.
        /// </summary>
        public static string SeleccioneEstadoProducto_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneEstadoProducto_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la marca.
        /// </summary>
        public static string SeleccioneMarca_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneMarca_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el rango el de precio.
        /// </summary>
        public static string SeleccioneRangoPrecio_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneRangoPrecio_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tipo de envase.
        /// </summary>
        public static string SeleccioneTipoEnvase_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneTipoEnvase_etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el tipo de producto.
        /// </summary>
        public static string SeleccioneTipoProducto_etiqueta {
            get {
                return ResourceManager.GetString("SeleccioneTipoProducto_etiqueta", resourceCulture);
            }
        }
    }
}
